<?php

namespace TomatoPHP\FilamentAccounts\Filament\Resources\AccountRequestResource\Pages;

use TomatoPHP\FilamentAccounts\Filament\Resources\AccountRequestResource;
use Filament\Actions;
use Filament\Resources\Pages\EditRecord;

class EditAccountRequest extends EditRecord
{
    protected static string $resource = AccountRequestResource::class;

    protected function getHeaderActions(): array
    {
        return [
            Actions\DeleteAction::make(),
        ];
    }

    protected function mutateFormDataBeforeSave(array $data): array
    {
        $data['user_id'] = auth()->id();
        if($data['is_approved']){
            $data['is_approved_at'] = now();
        }
        else {
            $data['is_approved_at'] = null;
        }
        return parent::mutateFormDataBeforeSave($data); // TODO: Change the autogenerated stub
    }
}
